### ISSUE TITLE
[v0.1.20] Script added key to HKEY_CLASSES_ROOT

### ISSUE THREAD

**Issue by mHaisham** [saleguas/context_menu#10]
If i'm not wrong as of **v0.1.20** registry keys should be added to `HKEY_CURRENT_USER\Software\Classes`. However my code (shown below) added the key to `HKEY_CLASSES_ROOT`.

```python
def command(*args, **kwargs):
    print(args)
    print(kwargs)
    input()


if __name__ == '__main__':
    from context_menu import menus

    menus.FastCommand('test', type='FILES', python=command).compile()
```

As a side-effect, remove menu says that key doesnt exist

**Comment by saleguas** [comment]
Hm, are you sure you updated the context_menu pip project? I don't see this behavior on my end.

**Comment by mHaisham** [comment]
Apparently you need to run to update

```python
pip install context_menu --upgrade
```
