### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by MicheleDeZen** [saleguas/context_menu#13]
Hi, i am trying to add the context menu functionality to a simple script i wrote but i can't get the example script to generate the menu. When i try to run it it doesn't get me any errors.

**Comment by saleguas** [comment]
Hello, what OS are you running it on? I just tried an example myself and it functioned properly. Make sure your 'type' is correct.

**Comment by MicheleDeZen** [comment]
hi, thanks for the reply i am on a windows machine

Michele De Zen

Il Mar 3 Nov 2020, 18:23 Salvador aleguas <notifications@github.com> ha
scritto:

**Comment by MicheleDeZen** [comment]
what is the different possibilities for 'type'? thaks a lot

**Comment by saleguas** [comment]
You can see the examples for the 'type' in the README documentaiton, as for the examples not working, I just tried the code on both a virtualized Linux and Windows system and it functioned perfectly. I'm going to close this issue for now, but if you have any more troubles or suspicion that it truly is an issue with the library, feel free to open another issue.

**Comment by FrtZgwL** [comment]
Hey everybody, I'm having the same issue. When I run `simple_fast_command.py` the program just ends with no error message and the context menu unchanged. I'm running Windows 10 Education Edition with Python 3.9. Can anyone help?

**Comment by dontbanmeplz** [comment]
same except im on python 3.10
