### ISSUE TITLE
Examples not working on Windows 11

### ISSUE THREAD

**Issue by Nauja** [saleguas/context_menu#24]
Hi,

I had a hard time with the provided examples on Windows 11, because in the Quickstart you say:

It's super easy! You can create entries in as little as 3 lines:
```
from context_menu import menus

fc = menus.FastCommand('Example Fast Command 1', type='FILES', command='echo Hello')
fc.compile()
```

With a screenshot of the menu on Windows.

However I don't know if that's a difference with older Windows, or because you wanted the examples to look crossplatform, or concises, but for me the FastCommand with `echo hello` doesn't work. In fact it has to be `cmd /c echo hello`.

Actually I test it with `pause` so that if there's a command prompt it doesn't disappear right away. With `pause`, Windows opens me a menu to choose how to open the file because the FastCommand doesn't work. With `cmd /c pause`,  the FastCommand works correctly and the command prompt opens.

Not saying that you should change the examples to include `cmd /c`, but right now the README makes it look like `echo hello` should work, and I spent many time trying to find why it didn't work for me 😅 . So the README should mention somewhere that if you want to do `echo hello`, the command actually has to be `cmd /c echo hello` on Windows

**Comment by fhabermacher** [comment]
Thanks your `cmd /c` tweak helped me run it on Win 11 @ py 11

**Comment by saleguas** [comment]
Thanks for raising this, I added a clarification note in the readme.
