### ISSUE TITLE
Window's submenu size limit

### ISSUE THREAD

**Issue by GanerCodes** [saleguas/context_menu#5]
The current, hard limit for how many items can be in a submenu is 16.
Could it be possible to change this somehow?

**Comment by saleguas** [comment]
I've tried and asked around on this question and I couldn't receive an answer anywhere. Unfortunately for now, there isn't a way to change it. However, there is a workaround with GUIs that I plan on implementing some time in the future.

**Comment by mHaisham** [comment]
There is a possible solution listed [here](https://stackoverflow.com/a/52623554/11728401)

It rises a primary concern **performance issues**.
So the question becomes, **is it worth** the performance risks?

**Comment by ganercrafter** [comment]
I'd say yes, assuming it isn't insane or anything

**Comment by GanerCodes** [comment]
switched to linux
