### ISSUE TITLE
[QUESTION] Running on VM - Ubuntu

### ISSUE THREAD

**Issue by l3str4nge** [saleguas/context_menu#6]
Hello, I am trying create fast command but it seems not working.  Did someone tried create context menus on VM?

My configuration:
HOST: Windows 7 64bit
GUEST: Ubuntu 20.04  64bit 
Running on Virtual Box 6.1

Thank's for any help.

**Comment by saleguas** [comment]
Hello, did you restart nautilus after running the command? And please post your code. Thanks.

**Comment by mateuszz0000** [comment]
```
from context_menu import menus
fc = menus.FastCommand('Example Fast Command 1', type='FILES', command='echo Hello')
fc.compile()
```

then `nautilus -q` then open file manager. Maybe i am missing something?

**Comment by saleguas** [comment]
Does the entry appear on the context menu? The way it interacts on Linux is quite weird and the shell being ran isn't the same shell that you probably have open (you won't have any output).

**Comment by susarlanikhilesh** [comment]
I tried the same. I'm also unable to see the context menu. What else should be done? @saleguas

**Comment by susarlanikhilesh** [comment]
Thank you. It worked. I am able to see the context menu @thescribe11
