### ISSUE TITLE
Display only on shift-click

### ISSUE THREAD

**Issue by mHaisham** [saleguas/context_menu#9]
### Windows
- adds an empty string value named Extended for key created

More on stackoverflow [post](https://stackoverflow.com/a/29769228/11728401)

### Linux
Not aware of the existance of the feature

**Comment by saleguas** [comment]
Wow! I can't believe I haven't seen this post before. There is a ton of useful information, especially installing a context menu without admin perms. Regardless, I could add the shift click option in the future. Thanks for sharing this!

**Comment by saleguas** [comment]
Removed admin rights and added exclusive support file files 39573cc
